services:
  db:
    image: postgres:16-alpine
    hostname: db
    volumes:
      - 'fine_db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: chudo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chudo -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  back:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: back
    environment:
      debug: "False"
    volumes:
      - '/var/media:/proj/media'
      - '/var/static:/var/static'
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  fine_db:
