apiVersion: v1
kind: ConfigMap
metadata:
  name: fine-app-config
  namespace: fine
data:
  debug: "False"
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: mydb
  DB_USER: chudo
  DB_HOST: postgres
  DB_PORT: "5432"
  CACHE_REDIS_URL: redis://redis:6379/1
---
apiVersion: v1
kind: Secret
metadata:
  name: fine-app-secret
  namespace: fine
type: Opaque
stringData:
  DB_PASSWORD: password
