# Generated by Django 4.1.4 on 2026-04-04 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0016_alter_usergroups_description_alter_usergroups_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usergroups',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_event', to='fine.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'rank'], name='user_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_recommendation'),
        ),
    ]
