# Generated by Django 4.1.4 on 2026-04-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fine", "0017_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
